### ISSUE TITLE
Do not use too much String as "Magicien" or "Guerrier"

### ISSUE THREAD

**Issue by Shetza** [ludivine-o/JAVA_003_DnD#3]
Could you refactor the abuse usage of String "Magicien" and "Guerrier" (and other characters later). May be use const or short letter code at first and something more efficiant and robust later ?

**Comment by ludivine-o** [comment]
MAGICIEN et GUERRIER sont maintenant des "public static final String" valant respectivement "M" et "G". Cest deux valeurs ne sont plus utilisées en tant que String dans le reste du code ...
